networks:
  arnelify-network:
    name: arnelify-network
    driver: bridge
    
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - ./:/var/www/node
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3001:3001"
    tty: true