// MIT LICENSE

// COPYRIGHT (R) 2025 ARNELIFY. AUTHOR: TARON SARKISYAN

// PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OBTAINING A COPY
// OF THIS SOFTWARE AND ASSOCIATED DOCUMENTATION FILES (THE "SOFTWARE"), TO DEAL
// IN THE SOFTWARE WITHOUT RESTRICTION, INCLUDING WITHOUT LIMITATION THE RIGHTS
// TO USE, COPY, MODIFY, MERGE, PUBLISH, DISTRIBUTE, SUBLICENSE, AND/OR SELL
// COPIES OF THE SOFTWARE, AND TO PERMIT PERSONS TO WHOM THE SOFTWARE IS
// FURNISHED TO DO SO, SUBJECT TO THE FOLLOWING CONDITIONS:

// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN ALL
// COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { Http1, Http1Opts, Http1Ctx, Http1Stream } from "./tcp1/http1";
import { Http2, Http2Opts, Http2Ctx, Http2Stream } from "./tcp1/http2";
import { WebSocket_, WebSocketOpts, WebSocketCtx, WebSocketBytes, WebSocketStream } from "./tcp1/ws";
import { Http3, Http3Opts, Http3Ctx, Http3Stream } from "./tcp2/http3";
import { WebTransport_, WebTransportOpts, WebTransportCtx, WebTransportBytes, WebTransportStream } from "./tcp2/wt";

export type { Http1Opts, Http1Ctx, Http1Stream };
export type { WebSocketOpts, WebSocketCtx, WebSocketBytes, WebSocketStream };
export type { Http2Opts, Http2Ctx, Http2Stream };
export type { Http3Opts, Http3Ctx, Http3Stream };
export type { WebTransportOpts, WebTransportCtx, WebTransportBytes, WebTransportStream };

export { Http1, WebSocket_, Http2, Http3, WebTransport_ };